package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.User;
import life.majiang.community.model.UserExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    int updateByPrimaryKeySelective(User record);

    @Select("select * from user where account_id=#{username} and password=#{password}")
    public User getByUsernameAndPassword(String username,String password);

    @Select("select * from user where account_id=#{username}")
    public User getByUsername(String username);

    @Insert("insert into user(account_id,name,gmt_create,gmt_modified,email,type,password,token,bio) values (#{accountId},#{name},#{gmtCreate},#{gmtModified},#{email},#{type},#{password},#{token},#{bio})")
    void create(User user);

    @Update("update user set token=#{token} where account_id=#{accountid}")
    void updateTokenByAccountId(String accountid,String token);

    @Update("update user set email=#{email},name=#{name},bio=#{bio} where account_id=#{accountId}")
    void updateInfoById(User user);

    @Update("update user set password=#{password} where account_id=#{accountId}")
    void updatePasswordById(User user);

    @Update("update user set avatar_url=#{avatarUrl} where account_id=#{accountId}")
    void updateAvatarUrlById(User user);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbg.generated Sun Oct 24 22:51:45 CST 2021
     */
    int updateByPrimaryKey(User record);
}